defaults:
- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: thress_ai_test_run

## WANDB params
# The wandb project name
project: threes-ai
# The wandb user to log to
entity: pyflynn
# The wandb group for the run
group: test_run_002

## ENV params
obs_space_kwargs: {}
reward_space_kwargs: {}

## TRAINING params
total_steps: 2e7
num_actors: 1
n_actor_envs: 1
unroll_length: 1
batch_size: 1
discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 4
hidden_dim: 32
embedding_dim: 16
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 3


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 5e-5
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.0002
baseline_cost: 1.
teacher_kl_cost: 0.005
teacher_baseline_cost: 0.0
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.9
reduction: sum

# Pretrained model for KL loss
use_teacher: False
teacher_load_dir:
teacher_checkpoint_file:

# MISCELLANEOUS params
use_mixed_precision: True
actor_device: cpu
learner_device: cpu
model_log_freq: 100
# file_descriptor or file_system
sharing_strategy: file_system
disable_wandb: True
debug: True
