defaults:
- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: autodl_b16_h128_e32_evaluation_1113_sample_true

## WANDB params
# The wandb project name
project: threes-ai
# The wandb user to log to
entity: pyflynn
# The wandb group for the run
group: evaluation_runs

## TRAINING params
total_steps: 3e9
num_actors: 7
num_buffers: 100
n_actor_envs: 8
unroll_length: 64
batch_size: 32

## MODEL params
model_arch: conv_model
n_blocks: 16
hidden_dim: 128
embedding_dim: 32
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 3

# MISCELLANEOUS params
use_mixed_precision: True
actor_device: cpu

# file_descriptor or file_system
sharing_strategy: file_system
disable_wandb: False
debug: False

load_dir: /Users/flynn.wang/repo/flynn/snapshot/autodl_b16_h128_e32_3e9_3090_restart5_dropin_updated
#checkpoint_file: 3451566080_weights.pt
checkpoint_file: 4144709632_weights.pt
weights_only: False
n_value_warmup_batches: 0
